### ISSUE TITLE
Unable to install through pip

### ISSUE THREAD

**Issue by iamkroot** [PhracturedBlue/fava-portfolio-summary#1]
Thanks for creating such a useful extension, has been really helpful!

## Problem
Doing a `pip install .` in the root directory after a clone is failing to install the package contents correctly. It didn't create a `fava_portfolio_summary` directory with the python files in the `site-packages` directory, and only copied the metadata to it.

## Solution
I was able to resolve it by adding the `package_dir` option to setup.py:
```python
...
packages=find_packages(),
package_dir={'fava_portfolio_summary': '.'}
...
```

PS: setuptools is deprecated, so it might be prudent to switch to `pyproject.toml` to specify the package details :)

PS2: Would be good to add some installation instructions to the readme. After the proposed change, doing `pip install git+https://github.com/PhracturedBlue/fava-portfolio-summary` does the job!

**Comment by PhracturedBlue** [comment]
Thanks for the feedback and patch
